### ISSUE TITLE
Infografía Realidad Aumentada 

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Litzy-lopez4#1]
[Infografía Realidad Aumentada_Litzy Lopez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Litzy-lopez4/files/14213338/Infografia.Realidad.Aumentada_Litzy.Lopez.pdf)

**Comment by ElisabetRD** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
